image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    init: |
      go mod download
      go install go.uber.org/mock/mockgen@latest
    command: echo "Ready! Run 'go test ./...' to verify"

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - golang.go
